# FROM rocker/rstudio:4.4.2
FROM rocker/r-ver:4.4.2

ARG NONMEM_MAJOR_VERSION=7
ARG NONMEM_MINOR_VERSION=5
ARG NONMEM_PATCH_VERSION=1
ENV NONMEM_VERSION_NO_DOTS=${NONMEM_MAJOR_VERSION}${NONMEM_MINOR_VERSION}${NONMEM_PATCH_VERSION}
ENV NONMEM_VERSION=${NONMEM_MAJOR_VERSION}.${NONMEM_MINOR_VERSION}.${NONMEM_PATCH_VERSION}

ARG NONMEMURL=https://nonmem.iconplc.com/nonmem${NONMEM_VERSION_NO_DOTS}/NONMEM${NONMEM_VERSION_NO_DOTS}.zip
ARG NONMEMZIPPASS=yorx8bqRT

ARG PSN_VERSION_MAJOR=5
ARG PSN_VERSION_MINOR=6
ARG PSN_VERSION_PATCH=0

ARG NMTHREADS=4

ARG PSN_VERSION=${PSN_VERSION_MAJOR}.${PSN_VERSION_MINOR}.${PSN_VERSION_PATCH}
ARG PSN_VERSION_UNDERSCORE=${PSN_VERSION_MAJOR}_${PSN_VERSION_MINOR}_${PSN_VERSION_PATCH}
ARG PSNURL=https://github.com/UUPharmacometrics/PsN/releases/download/v${PSN_VERSION}/PsN-${PSN_VERSION}.tar.gz

ARG R_library="'languageserver', 'xpose', 'xpose4', 'dplyr', 'ggpubr', 'reshape', 'ggplot2', 'rxode2', 'nlmixr2', 'devtools', 'colorspace', 'autoReg', 'eha', 'flextable', 'ftExtra', 'interpretCI', 'ranger', 'survex', 'survminer'"

USER root

# Update & add the PPA
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get install -y gfortran-11 && \
    # Set gfortran-11 as the default
    update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-11 100 && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* \
    && apt-get update \
    && apt-get install -y \
        curl \
        git \
        python3 \
        python3-venv \
        python3-dev \
        make \
        cpanminus \
        libmpich-dev \
        mpich \
        wget \
        unzip \
        pandoc \
        libpq-dev \
        libcairo2-dev \
        libssl-dev \
        libcurl4-openssl-dev \
        libmariadb-dev \
        libgmp-dev \
        libmpfr-dev \
        libxml2-dev \
        libudunits2-dev \
        libblas-dev \
        liblapack-dev \
        libmagick++-dev \
        expect \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && cpanm Math::Random::Free Mouse MouseX::Params::Validate Archive::Zip YAML Capture::Tiny File::Copy::Recursive File::HomeDir Math::SigFigs Statistics::Distributions Math::Matrix Math::Random Math::MatrixReal \
    && R -e "install.packages(c(${R_library})); devtools::install_github('kassambara/ggpubr'); devtools::install_github('UUPharmacometrics/PsNR')"

ADD ${PSNURL} /tmp/psn.tar.gz
RUN tar zxf /tmp/psn.tar.gz -C /mnt \
    && mkdir -p /opt/NONMEM/nm${NONMEM_VERSION_NO_DOTS}/license &&echo "this_is_fake_license" > /opt/NONMEM/nm${NONMEM_VERSION_NO_DOTS}/license/nonmem.lic

# Download and install NONMEM
RUN COOKIES_FILE=$(mktemp) \
    && curl -c "$COOKIES_FILE" https://nonmem.iconplc.com/ > /dev/null \
    && CSRF_TOKEN=$(grep 'csrftoken' "$COOKIES_FILE" | head -n 1 | awk '{print $7}') \
    && DOWNLOAD_URL="${NONMEMURL}?csrftoken=${CSRF_TOKEN}" \
    && curl -b "$COOKIES_FILE" -o /tmp/NONMEM.zip "$DOWNLOAD_URL" \
    && rm "$COOKIES_FILE" \
    && cd /tmp \
    && unzip -P ${NONMEMZIPPASS} NONMEM.zip \
    && ls /tmp \
    && if [ ! -d "/tmp/nm${NONMEM_VERSION_NO_DOTS}CD" ] ; then ln -s . nm${NONMEM_VERSION_NO_DOTS}CD ; fi \
    && cd /tmp/nm${NONMEM_VERSION_NO_DOTS}CD \
    && bash \
    SETUP${NONMEM_MAJOR_VERSION}${NONMEM_MINOR_VERSION} \
    /tmp/nm${NONMEM_VERSION_NO_DOTS}CD \
    /opt/NONMEM/nm${NONMEM_VERSION_NO_DOTS} \
    gfortran \
    y \
    /usr/bin/ar \
    same \
    rec \
    q \
    unzip \
    nonmem${NONMEM_MAJOR_VERSION}${NONMEM_MINOR_VERSION}e.zip \
    nonmem${NONMEM_MAJOR_VERSION}${NONMEM_MINOR_VERSION}r.zip \
    && ln -s /opt/NONMEM/nm${NONMEM_VERSION_NO_DOTS} /opt/NONMEM/nm_current \
    && ln -s /opt/NONMEM/nm_current/util/nmfe${NONMEM_MAJOR_VERSION}${NONMEM_MINOR_VERSION} \
    /opt/NONMEM/nm_current/util/nmfe \
    && rm -r /tmp/* \
    && rm -f /opt/NONMEM/nm_current/mpi/mpi_ling/libmpich.a \
    && ln -s \
    /usr/lib/x86_64-linux-gnu/libmpich.a \
    /opt/NONMEM/nm_current/mpi/mpi_ling/libmpich.a \
    && echo "Update the default number of nodes for parallel NONMEM in the mpilinux_XX.pnm file" \
    && for NMNODES in 2 4 6 8 10 12 14 16 18 20 22 24 28 32 48 64 128; do \
    sed 's/\[nodes\]=8/\[nodes\]='$NMNODES'/' \
    /opt/NONMEM/nm_current/run/mpilinux8.pnm > \
    /opt/NONMEM/nm_current/run/mpilinux_$NMNODES.pnm ; \
    done

# add nonmem to environment
ENV PATH=/opt/NONMEM/nm${NONMEM_VERSION_NO_DOTS}/run:$PATH

# making shortcuts for nonmem (in consideration of PsN)
RUN cd / \
    && mkdir -p /opt/NONMEM \
    && ln -sf /opt/NONMEM/nm${NONMEM_VERSION_NO_DOTS} /opt/NONMEM/nm_current \
    && ln -sf /opt/NONMEM/nm_current/util/nmfe${NONMEM_MAJOR_VERSION}${NONMEM_MINOR_VERSION} \
    /opt/NONMEM/nm_current/util/nmfe

# configure PsN
RUN cd /mnt/PsN-Source && expect <<EOF
set timeout -1c
spawn perl setup.pl
expect {
    -re {Would you like help to create a configuration file} {
        send "y\r"
        exp_continue
    }
    -re {Would you like to add another one \[y/n\]} {
        send "n\r"
        exp_continue
    }
    -re {\[y/n\]} {
        send "n\r"
        exp_continue
    }
    -re {\[([\w\d/\.])+\]} {
        send "\r"
        exp_continue
    }
    -re {use the name nm\d+} {
        send "\r"
        exp_continue
    }
    -re {to exit the installation program} {
        send "\r"
    }
}
EOF

RUN export TEMP_PERL_VERSION=$(perl -v | grep -oP '(?<=\(v)[^)]*') && \
    export TEMP_PSN_CONF_PATH=/usr/local/share/perl/$(perl -v | grep -oP '(?<=\(v)[^)]*')/PsN_${PSN_VERSION_UNDERSCORE}/psn.conf && \
    mv $TEMP_PSN_CONF_PATH /mnt/psn.conf && \
    sed 's/threads=5/threads='${NMTHREADS}'/' /mnt/psn.conf > $TEMP_PSN_CONF_PATH && \
    PSN_NONMEM_VERSION=$(echo $NONMEM_VERSION | sed 's/\.[0-9]$//g') && \
    MPICOUNT=$(for MPINAME in /opt/NONMEM/nm_current/run/mpilinux_[0-9]*.pnm; do echo $(basename $MPINAME | sed 's/[^0-9]*//g'); done | sort -n) && \
    for PARACOUNT in $MPICOUNT; do \
        printf "parallel${PARACOUNT}=/opt/NONMEM/nm_current,${PSN_NONMEM_VERSION}\n" >> $TEMP_PSN_CONF_PATH; \
    done && \
    printf "\n\n" >> $TEMP_PSN_CONF_PATH && \
    for PARACOUNT in $MPICOUNT; do \
        printf "[default_options_parallel${PARACOUNT}]\nparafile=/opt/NONMEM/nm_current/run/mpilinux_${PARACOUNT}.pnm\n" >> $TEMP_PSN_CONF_PATH; \
    done

RUN mkdir -p /opt/PsN/current

WORKDIR /workspace