services:
  app:
    # build:
    #   dockerfile: dockerfile
    #   args:
    #     NONMEM_MAJOR_VERSION: 7
    #     NONMEM_MINOR_VERSION: 5
    #     NONMEM_PATCH_VERSION: 1
    #     PSN_VERSION_MAJOR: 5
    #     PSN_VERSION_MINOR: 3
    #     PSN_VERSION_PATCH: 2
    #     PERL_VERSION: 5.34.0
    image: swgoo/nonmem:7.5.1-PsN-5.3.2
    working_dir: /workspace
    volumes:
      - ./nonmem.lic:/opt/NONMEM/nm_current/license/nonmem.lic
      - ../workspace:/workspace
    command: sleep infinity
