services:
  app:
    ##### Uncomment the following lines to build the image locally #####
    # build:
    #   dockerfile: dockerfile
    #   args:
    #     NONMEM_MAJOR_VERSION: 7
    #     NONMEM_MINOR_VERSION: 5
    #     NONMEM_PATCH_VERSION: 1
    #     PSN_VERSION_MAJOR: 5
    #     PSN_VERSION_MINOR: 3
    #     PSN_VERSION_PATCH: 2
    #####
    ##### Comment out the following line if you build the image locally #####
    image: swgoo/nonmem
    #####
    working_dir: /workspace
    volumes:
      - ./nonmem.lic:/opt/NONMEM/nm_current/license/nonmem.lic
      - ..:/workspace
    command: sleep infinity
